### ISSUE TITLE
Missing date column in China-processed

### ISSUE THREAD

**Issue by dpa9694** [bolliger32/gpl-covid#49] opened 2020-03-27 04:28 UTC
The date column is missing in `data/processed/adm2/CHN_processed.csv`

**Comment by dpa9694** [comment] 2020-03-27 16:20
@luna983 I noticed that `cutoff_dates.csv` column ` end_date` has a trailing white space

**Comment by luna983** [comment] 2020-03-27 16:43
Thanks for opening up the issue! The leading white space is also an issue that should be fixed (PR submitted).

This is caused by pandas automatically dropping index columns that are not used as keys in `pd.merge`. Fixed in #51 . Thanks!

**Closed** 2020-03-27 16:47 UTC
